trigger:
  branches:
    include:
      - main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: 'sc-acr-ob-dev'
  imageRepository: 'online-boutique/frontend'
  dockerfilePath: 'application/online-boutique/src/frontend/Dockerfile'
  buildContext: 'application/online-boutique/src/frontend'
  tag: '$(Build.BuildId)'

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and Push

  jobs:
  - job: DockerBuild

    steps:
    - checkout: self

    - task: Docker@2
      displayName: Build and Push Frontend

      inputs:
        command: buildAndPush
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        Dockerfile: $(dockerfilePath)
        buildContext: $(buildContext)
        tags: |
          $(tag)
          latest